// Country list with flag emojis and names in multiple languages
// Flags use Unicode regional indicator symbols (works on iOS/Android)

export interface Country {
  code: string;        // ISO 3166-1 alpha-2
  flag: string;        // Unicode flag emoji
  name: {              // Names in all supported languages
    en: string;
    pt: string;
    fr: string;
    es: string;
    'es-US': string;
    zh: string;
    ja: string;
    ko: string;
    vi: string;
    tl: string;
    ar: string;
    ru: string;
    hi: string;
    bn: string;
    ln: string;
  };
}

// Convert country code to flag emoji
export function countryCodeToFlag(code: string): string {
  return code
    .toUpperCase()
    .split('')
    .map(char => String.fromCodePoint(0x1F1E6 + char.charCodeAt(0) - 65))
    .join('');
}

// List of countries most relevant for US immigrants
export const COUNTRIES: Country[] = [
  {
    code: 'US',
    flag: '🇺🇸',
    name: {
      en: 'United States',
      pt: 'Estados Unidos',
      fr: 'États-Unis',
      es: 'Estados Unidos',
      'es-US': 'Estados Unidos',
      zh: '美国',
      ja: 'アメリカ合衆国',
      ko: '미국',
      vi: 'Hoa Kỳ',
      tl: 'Estados Unidos',
      ar: 'الولايات المتحدة',
      ru: 'США',
      hi: 'अमेरिका',
      bn: 'যুক্তরাষ্ট্র',
      ln: 'Etats-Unis',
    },
  },
  {
    code: 'MX',
    flag: '🇲🇽',
    name: {
      en: 'Mexico',
      pt: 'México',
      fr: 'Mexique',
      es: 'México',
      'es-US': 'México',
      zh: '墨西哥',
      ja: 'メキシコ',
      ko: '멕시코',
      vi: 'México',
      tl: 'Mexico',
      ar: 'المكسيك',
      ru: 'Мексика',
      hi: 'मैक्सिको',
      bn: 'মেক্সিকো',
      ln: 'Mexique',
    },
  },
  {
    code: 'GT',
    flag: '🇬🇹',
    name: {
      en: 'Guatemala',
      pt: 'Guatemala',
      fr: 'Guatemala',
      es: 'Guatemala',
      'es-US': 'Guatemala',
      zh: '危地马拉',
      ja: 'グアテマラ',
      ko: '과테라',
      vi: 'Guatemala',
      tl: 'Guatemala',
      ar: 'غواتيمالا',
      ru: 'Гватемала',
      hi: 'ग्वाटेमाला',
      bn: 'গুয়াতেমালা',
      ln: 'Guatemala',
    },
  },
  {
    code: 'HN',
    flag: '🇭🇳',
    name: {
      en: 'Honduras',
      pt: 'Honduras',
      fr: 'Honduras',
      es: 'Honduras',
      'es-US': 'Honduras',
      zh: '洪都拉斯',
      ja: 'ホンジュラス',
      ko: '온두라스',
      vi: 'Honduras',
      tl: 'Honduras',
      ar: 'هندوراس',
      ru: 'Гондурас',
      hi: 'होंडुरास',
      bn: 'হন্দুরাস',
      ln: 'Honduras',
    },
  },
  {
    code: 'SV',
    flag: '🇸🇻',
    name: {
      en: 'El Salvador',
      pt: 'El Salvador',
      fr: 'El Salvador',
      es: 'El Salvador',
      'es-US': 'El Salvador',
      zh: '萨尔瓦多',
      ja: 'エルサルバドル',
      ko: '엘살바도르',
      vi: 'El Salvador',
      tl: 'El Salvador',
      ar: 'السلفادور',
      ru: 'Сальвадор',
      hi: 'अल सल्वाडोर',
      bn: 'এল সালভাদর',
      ln: 'El Salvador',
    },
  },
  {
    code: 'NI',
    flag: '🇳🇮',
    name: {
      en: 'Nicaragua',
      pt: 'Nicarágua',
      fr: 'Nicaragua',
      es: 'Nicaragua',
      'es-US': 'Nicaragua',
      zh: '尼加拉瓜',
      ja: 'ニカラグア',
      ko: '니카라과',
      vi: 'Nicaragua',
      tl: 'Nicaragua',
      ar: 'نيكاراغوا',
      ru: 'Никарагуа',
      hi: 'निकारागुआ',
      bn: 'নিকারাগুয়া',
      ln: 'Nicaragua',
    },
  },
  {
    code: 'CR',
    flag: '🇨🇷',
    name: {
      en: 'Costa Rica',
      pt: 'Costa Rica',
      fr: 'Costa Rica',
      es: 'Costa Rica',
      'es-US': 'Costa Rica',
      zh: '哥斯达黎加',
      ja: 'コスタリカ',
      ko: '코스타리카',
      vi: 'Costa Rica',
      tl: 'Costa Rica',
      ar: 'كوستاريكا',
      ru: 'Коста-Рика',
      hi: 'कोस्टा रिका',
      bn: 'কোস্টা রিকা',
      ln: 'Costa Rica',
    },
  },
  {
    code: 'PA',
    flag: '🇵🇦',
    name: {
      en: 'Panama',
      pt: 'Panamá',
      fr: 'Panama',
      es: 'Panamá',
      'es-US': 'Panamá',
      zh: '巴拿马',
      ja: 'パナマ',
      ko: '파나마',
      vi: 'Panama',
      tl: 'Panama',
      ar: 'بنما',
      ru: 'Панама',
      hi: 'पनामा',
      bn: 'পানামা',
      ln: 'Panama',
    },
  },
  {
    code: 'CO',
    flag: '🇨🇴',
    name: {
      en: 'Colombia',
      pt: 'Colômbia',
      fr: 'Colombie',
      es: 'Colombia',
      'es-US': 'Colombia',
      zh: '哥伦比亚',
      ja: 'コロンビア',
      ko: '콜롬비아',
      vi: 'Colombia',
      tl: 'Colombia',
      ar: 'كولومبيا',
      ru: 'Колумбия',
      hi: 'कोलंबिया',
      bn: 'কলম্বিয়া',
      ln: 'Colombie',
    },
  },
  {
    code: 'VE',
    flag: '🇻🇪',
    name: {
      en: 'Venezuela',
      pt: 'Venezuela',
      fr: 'Venezuela',
      es: 'Venezuela',
      'es-US': 'Venezuela',
      zh: '委内瑞拉',
      ja: 'ベネズエラ',
      ko: '베네수엘라',
      vi: 'Venezuela',
      tl: 'Venezuela',
      ar: 'فنزويلا',
      ru: 'Венесуэла',
      hi: 'वेनेजुएला',
      bn: 'ভেনেজুয়েলা',
      ln: 'Venezuela',
    },
  },
  {
    code: 'EC',
    flag: '🇪🇨',
    name: {
      en: 'Ecuador',
      pt: 'Equador',
      fr: 'Équateur',
      es: 'Ecuador',
      'es-US': 'Ecuador',
      zh: '厄瓜多尔',
      ja: 'エクアドル',
      ko: '에콰도르',
      vi: 'Ecuador',
      tl: 'Ecuador',
      ar: 'الإكوادور',
      ru: 'Эквадор',
      hi: 'इक्वाडोर',
      bn: 'ইকুয়েডর',
      ln: 'Équateur',
    },
  },
  {
    code: 'PE',
    flag: '🇵🇪',
    name: {
      en: 'Peru',
      pt: 'Peru',
      fr: 'Pérou',
      es: 'Perú',
      'es-US': 'Perú',
      zh: '秘鲁',
      ja: 'ペルー',
      ko: '페루',
      vi: 'Peru',
      tl: 'Peru',
      ar: 'بيرو',
      ru: 'Перу',
      hi: 'पेरू',
      bn: 'পেরু',
      ln: 'Pérou',
    },
  },
  {
    code: 'BR',
    flag: '🇧🇷',
    name: {
      en: 'Brazil',
      pt: 'Brasil',
      fr: 'Brésil',
      es: 'Brasil',
      'es-US': 'Brasil',
      zh: '巴西',
      ja: 'ブラジル',
      ko: '브라질',
      vi: 'Brazil',
      tl: 'Brazil',
      ar: 'البرازيل',
      ru: 'Бразилия',
      hi: 'ब्राज़ील',
      bn: 'ব্রাজিল',
      ln: 'Brésil',
    },
  },
  {
    code: 'CU',
    flag: '🇨🇺',
    name: {
      en: 'Cuba',
      pt: 'Cuba',
      fr: 'Cuba',
      es: 'Cuba',
      'es-US': 'Cuba',
      zh: '古巴',
      ja: 'キューバ',
      ko: '쿠바',
      vi: 'Cuba',
      tl: 'Cuba',
      ar: 'كوبا',
      ru: 'Куба',
      hi: 'क्यूबा',
      bn: 'কিউবা',
      ln: 'Cuba',
    },
  },
  {
    code: 'DO',
    flag: '🇩🇴',
    name: {
      en: 'Dominican Republic',
      pt: 'República Dominicana',
      fr: 'République dominicaine',
      es: 'República Dominicana',
      'es-US': 'República Dominicana',
      zh: '多米尼加共和国',
      ja: 'ドミニカ共和国',
      ko: '도미니카 공화국',
      vi: 'Cộng hòa Dominica',
      tl: 'Dominican Republic',
      ar: 'جمهورية الدومينيكان',
      ru: 'Доминиканская Республика',
      hi: 'डोमिनिकन गणराज्य',
      bn: 'ডোমিনিকান প্রজাতন্ত্র',
      ln: 'République dominicaine',
    },
  },
  {
    code: 'HT',
    flag: '🇭🇹',
    name: {
      en: 'Haiti',
      pt: 'Haiti',
      fr: 'Haïti',
      es: 'Haití',
      'es-US': 'Haití',
      zh: '海地',
      ja: 'ハイチ',
      ko: '아이티',
      vi: 'Haiti',
      tl: 'Haiti',
      ar: 'هايتي',
      ru: 'Гаити',
      hi: 'हैती',
      bn: 'হাইতি',
      ln: 'Haïti',
    },
  },
  {
    code: 'JM',
    flag: '🇯🇲',
    name: {
      en: 'Jamaica',
      pt: 'Jamaica',
      fr: 'Jamaïque',
      es: 'Jamaica',
      'es-US': 'Jamaica',
      zh: '牙买加',
      ja: 'ジャマイカ',
      ko: '자메이카',
      vi: 'Jamaica',
      tl: 'Jamaica',
      ar: 'جامايكا',
      ru: 'Ямайка',
      hi: 'जमैका',
      bn: 'জামাইকা',
      ln: 'Jamaïque',
    },
  },
  {
    code: 'CN',
    flag: '🇨🇳',
    name: {
      en: 'China',
      pt: 'China',
      fr: 'Chine',
      es: 'China',
      'es-US': 'China',
      zh: '中国',
      ja: '中国',
      ko: '중국',
      vi: 'Trung Quốc',
      tl: 'Tsina',
      ar: 'الصين',
      ru: 'Китай',
      hi: 'चीन',
      bn: 'চীন',
      ln: 'Chine',
    },
  },
  {
    code: 'IN',
    flag: '🇮🇳',
    name: {
      en: 'India',
      pt: 'Índia',
      fr: 'Inde',
      es: 'India',
      'es-US': 'India',
      zh: '印度',
      ja: 'インド',
      ko: '인도',
      vi: 'Ấn Độ',
      tl: 'India',
      ar: 'الهند',
      ru: 'Индия',
      hi: 'भारत',
      bn: 'ভারত',
      ln: 'Inde',
    },
  },
  {
    code: 'PH',
    flag: '🇵🇭',
    name: {
      en: 'Philippines',
      pt: 'Filipinas',
      fr: 'Philippines',
      es: 'Filipinas',
      'es-US': 'Filipinas',
      zh: '菲律宾',
      ja: 'フィリピン',
      ko: '필리핀',
      vi: 'Philippines',
      tl: 'Pilipinas',
      ar: 'الفلبين',
      ru: 'Филиппины',
      hi: 'फिलीपींस',
      bn: 'ফিলিপাইন',
      ln: 'Philippines',
    },
  },
  {
    code: 'KR',
    flag: '🇰🇷',
    name: {
      en: 'South Korea',
      pt: 'Coreia do Sul',
      fr: 'Corée du Sud',
      es: 'Corea del Sur',
      'es-US': 'Corea del Sur',
      zh: '韩国',
      ja: '韓国',
      ko: '한국',
      vi: 'Hàn Quốc',
      tl: 'South Korea',
      ar: 'كوريا الجنوبية',
      ru: 'Южная Корея',
      hi: 'दक्षिण कोरिया',
      bn: 'দক্ষিণ কোরিয়া',
      ln: 'Corée du Sud',
    },
  },
  {
    code: 'VN',
    flag: '🇻🇳',
    name: {
      en: 'Vietnam',
      pt: 'Vietnã',
      fr: 'Viêt Nam',
      es: 'Vietnam',
      'es-US': 'Vietnam',
      zh: '越南',
      ja: 'ベトナム',
      ko: '베트남',
      vi: 'Việt Nam',
      tl: 'Vietnam',
      ar: 'فيتنام',
      ru: 'Вьетнам',
      hi: 'वियतनाम',
      bn: 'ভিয়েতনাম',
      ln: 'Viêt Nam',
    },
  },
  {
    code: 'NG',
    flag: '🇳🇬',
    name: {
      en: 'Nigeria',
      pt: 'Nigéria',
      fr: 'Nigeria',
      es: 'Nigeria',
      'es-US': 'Nigeria',
      zh: '尼日利亚',
      ja: 'ナイジェリア',
      ko: '나이지리아',
      vi: 'Nigeria',
      tl: 'Nigeria',
      ar: 'نيجيريا',
      ru: 'Нигерия',
      hi: 'नाइजीरिया',
      bn: 'নাইজেরিয়া',
      ln: 'Nigeria',
    },
  },
  {
    code: 'GH',
    flag: '🇬🇭',
    name: {
      en: 'Ghana',
      pt: 'Gana',
      fr: 'Ghana',
      es: 'Ghana',
      'es-US': 'Ghana',
      zh: '加纳',
      ja: 'ガーナ',
      ko: '가나',
      vi: 'Ghana',
      tl: 'Ghana',
      ar: 'غانا',
      ru: 'Гана',
      hi: 'घाना',
      bn: 'ঘানা',
      ln: 'Ghana',
    },
  },
  {
    code: 'ET',
    flag: '🇪🇹',
    name: {
      en: 'Ethiopia',
      pt: 'Etiópia',
      fr: 'Éthiopie',
      es: 'Etiopía',
      'es-US': 'Etiopía',
      zh: '埃塞俄比亚',
      ja: 'エチオピア',
      ko: '에티오피아',
      vi: 'Ethiopia',
      tl: 'Ethiopia',
      ar: 'إثيوبيا',
      ru: 'Эфиопия',
      hi: 'इथियोपिया',
      bn: 'ইথিওপিয়া',
      ln: 'Éthiopie',
    },
  },
  {
    code: 'SO',
    flag: '🇸🇴',
    name: {
      en: 'Somalia',
      pt: 'Somália',
      fr: 'Somalie',
      es: 'Somalia',
      'es-US': 'Somalia',
      zh: '索马里',
      ja: 'ソマリア',
      ko: '소말리아',
      vi: 'Somalia',
      tl: 'Somalia',
      ar: 'الصومال',
      ru: 'Сомали',
      hi: 'सोमालिया',
      bn: 'সোমালিয়া',
      ln: 'Somalie',
    },
  },
  {
    code: 'SY',
    flag: '🇸🇾',
    name: {
      en: 'Syria',
      pt: 'Síria',
      fr: 'Syrie',
      es: 'Siria',
      'es-US': 'Siria',
      zh: '叙利亚',
      ja: 'シリア',
      ko: '시리아',
      vi: 'Syria',
      tl: 'Syria',
      ar: 'سوريا',
      ru: 'Сирия',
      hi: 'सीरिया',
      bn: 'সিরিয়া',
      ln: 'Syrie',
    },
  },
  {
    code: 'AF',
    flag: '🇦🇫',
    name: {
      en: 'Afghanistan',
      pt: 'Afeganistão',
      fr: 'Afghanistan',
      es: 'Afganistán',
      'es-US': 'Afganistán',
      zh: '阿富汗',
      ja: 'アフガニスタン',
      ko: '아프가니스탄',
      vi: 'Afghanistan',
      tl: 'Afghanistan',
      ar: 'أفغانستان',
      ru: 'Афганистан',
      hi: 'अफ़ग़ानिस्तान',
      bn: 'আফগানিস্তান',
      ln: 'Afghanistan',
    },
  },
  {
    code: 'UA',
    flag: '🇺🇦',
    name: {
      en: 'Ukraine',
      pt: 'Ucrânia',
      fr: 'Ukraine',
      es: 'Ucrania',
      'es-US': 'Ucrania',
      zh: '乌克兰',
      ja: 'ウクライナ',
      ko: '우크라이나',
      vi: 'Ukraine',
      tl: 'Ukraine',
      ar: 'أوكرانيا',
      ru: 'Украина',
      hi: 'यूक्रेन',
      bn: 'ইউক্রেন',
      ln: 'Ukraine',
    },
  },
  {
    code: 'RU',
    flag: '🇷🇺',
    name: {
      en: 'Russia',
      pt: 'Rússia',
      fr: 'Russie',
      es: 'Rusia',
      'es-US': 'Rusia',
      zh: '俄罗斯',
      ja: 'ロシア',
      ko: '러시아',
      vi: 'Nga',
      tl: 'Russia',
      ar: 'روسيا',
      ru: 'Россия',
      hi: 'रूस',
      bn: 'রাশিয়া',
      ln: 'Russie',
    },
  },
  {
    code: 'CA',
    flag: '🇨🇦',
    name: {
      en: 'Canada',
      pt: 'Canadá',
      fr: 'Canada',
      es: 'Canadá',
      'es-US': 'Canadá',
      zh: '加拿大',
      ja: 'カナダ',
      ko: '캐나다',
      vi: 'Canada',
      tl: 'Canada',
      ar: 'كندا',
      ru: 'Канада',
      hi: 'कनाडा',
      bn: 'কানাডা',
      ln: 'Canada',
    },
  },
  {
    code: 'GB',
    flag: '🇬🇧',
    name: {
      en: 'United Kingdom',
      pt: 'Reino Unido',
      fr: 'Royaume-Uni',
      es: 'Reino Unido',
      'es-US': 'Reino Unido',
      zh: '英国',
      ja: 'イギリス',
      ko: '영국',
      vi: 'Vương quốc Anh',
      tl: 'United Kingdom',
      ar: 'المملكة المتحدة',
      ru: 'Великобритания',
      hi: 'ब्रिटेन',
      bn: 'যুক্তরাজ্য',
      ln: 'Royaume-Uni',
    },
  },
  {
    code: 'DE',
    flag: '🇩🇪',
    name: {
      en: 'Germany',
      pt: 'Alemanha',
      fr: 'Allemagne',
      es: 'Alemania',
      'es-US': 'Alemania',
      zh: '德国',
      ja: 'ドイツ',
      ko: '독일',
      vi: 'Đức',
      tl: 'Germany',
      ar: 'ألمانيا',
      ru: 'Германия',
      hi: 'जर्मनी',
      bn: 'জার্মানি',
      ln: 'Allemagne',
    },
  },
  {
    code: 'FR',
    flag: '🇫🇷',
    name: {
      en: 'France',
      pt: 'França',
      fr: 'France',
      es: 'Francia',
      'es-US': 'Francia',
      zh: '法国',
      ja: 'フランス',
      ko: '프랑스',
      vi: 'Pháp',
      tl: 'France',
      ar: 'فرنسا',
      ru: 'Франция',
      hi: 'फ़्रांस',
      bn: 'ফ্রান্স',
      ln: 'France',
    },
  },
  {
    code: 'ES',
    flag: '🇪🇸',
    name: {
      en: 'Spain',
      pt: 'Espanha',
      fr: 'Espagne',
      es: 'España',
      'es-US': 'España',
      zh: '西班牙',
      ja: 'スペイン',
      ko: '스페인',
      vi: 'Tây Ban Nha',
      tl: 'Spain',
      ar: 'إسبانيا',
      ru: 'Испания',
      hi: 'स्पेन',
      bn: 'স্পেন',
      ln: 'Espagne',
    },
  },
  {
    code: 'IT',
    flag: '🇮🇹',
    name: {
      en: 'Italy',
      pt: 'Itália',
      fr: 'Italie',
      es: 'Italia',
      'es-US': 'Italia',
      zh: '意大利',
      ja: 'イタリア',
      ko: '이탈리아',
      vi: 'Ý',
      tl: 'Italy',
      ar: 'إيطاليا',
      ru: 'Италия',
      hi: 'इटली',
      bn: 'ইতালি',
      ln: 'Italie',
    },
  },
  {
    code: 'JP',
    flag: '🇯🇵',
    name: {
      en: 'Japan',
      pt: 'Japão',
      fr: 'Japon',
      es: 'Japón',
      'es-US': 'Japón',
      zh: '日本',
      ja: '日本',
      ko: '일본',
      vi: 'Nhật Bản',
      tl: 'Japan',
      ar: 'اليابان',
      ru: 'Япония',
      hi: 'जापान',
      bn: 'জাপান',
      ln: 'Japon',
    },
  },
  {
    code: 'AU',
    flag: '🇦🇺',
    name: {
      en: 'Australia',
      pt: 'Austrália',
      fr: 'Australie',
      es: 'Australia',
      'es-US': 'Australia',
      zh: '澳大利亚',
      ja: 'オーストラリア',
      ko: '호주',
      vi: 'Úc',
      tl: 'Australia',
      ar: 'أستراليا',
      ru: 'Австралия',
      hi: 'ऑस्ट्रेलिया',
      bn: 'অস্ট্রেলিয়া',
      ln: 'Australie',
    },
  },
];

/**
 * Get country name by language
 */
export function getCountryName(country: Country, lang: string): string {
  const langKey = lang as keyof typeof country.name;
  return country.name[langKey] || country.name.en;
}

/**
 * Search countries by name (in any language)
 */
export function searchCountries(query: string, lang: string): Country[] {
  const lowerQuery = query.toLowerCase();
  return COUNTRIES.filter(country => {
    const name = getCountryName(country, lang).toLowerCase();
    return name.includes(lowerQuery) || country.code.toLowerCase().includes(lowerQuery);
  });
}
